### ISSUE TITLE
"No LPD8 Controller found" on Ubuntu 18.04

### ISSUE THREAD

**Issue by redlotusaustin** [zetof/LPD8#1]
Like the title says, main.py exits with "No LPD8 Controller found", even though dmesg lists the LPD8:

`[196339.917475] usb 1-1: new full-speed USB device number 7 using xhci_hcd
[196340.067192] usb 1-1: New USB device found, idVendor=09e8, idProduct=0075, bcdDevice= 1.00
[196340.067198] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[196340.067201] usb 1-1: Product: LPD8
[196340.067204] usb 1-1: Manufacturer: AKAI professional LLC
[196537.792837] r8169 0000:04:00.0 enp4s0: Link is Down
spic@lotus:~/sequencer/LPD8-master$ python3 main.py 
*** No LPD8 Controller found ***
`

**Comment by zetof** [comment]
Hello, nice you tried it! To be honest, you're the first one who has tried it and I never tested it on Ubuntu.
It could be a naming problem from rtmidi library. Would you mind to try this:

In lpd8.py:

    def _get_midi_device(self, devices_list):
        midi_device = None
        midi_ports = devices_list.get_ports()
        if len(midi_ports) != 0:
            index = 0
            for name in midi_ports:
                print(name) <-- Add this line
                if name == self.NAME:
                    devices_list.open_port(index)
                    midi_device = devices_list
                index += 1
        return midi_device

And send me the output?
Thanks!

**Comment by zetof** [comment]
OK, I've found it. I was strictly checking on string "LPD8" which is fine on Mac OS. Tried it on Ubuntu, I get:

0 Midi Through:Midi Through Port-0 14:0
1 LPD8:LPD8 MIDI 1 24:0
0 Midi Through:Midi Through Port-0 14:0
1 LPD8:LPD8 MIDI 1 24:0
2 RtMidiIn Client:RtMidi input 128:0

So I made it more permissive on finding PAD

**Comment by redlotusaustin** [comment]
Thanks for the quick response! It looks like the pad is recognized but now the program crashes when a pad is pressed:

```
spic@lotus:~/sequencer/LPD8$ python3 main.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/spic/sequencer/LPD8/lpd8/lpd8.py", line 72, in run
    self._read_midi()
  File "/home/spic/sequencer/LPD8/lpd8/lpd8.py", line 57, in _read_midi
    pad_value = self._pads.note_on(cmd - self.NOTE_ON + 1, ctrl, msg[0][2])
  File "/home/spic/sequencer/LPD8/lpd8/pads.py", line 132, in note_on
    return self._pads[program][self._pad_index[pad]].note_on(velocity)
KeyError: 36
```
